### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [karimnaaji/vectiler#10]
I would like to point out that an identifier like "[`stbi__sse2_available`](https://github.com/karimnaaji/vectiler/blob/35d673c4e885f8d2a8b5dc0d442d5efd7deed533/src/stb_image.h#L704)" [does eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by karimnaaji** [comment]
This file is part of the [stb libraries](https://github.com/nothings/stb), where you can directly open an issue there.

If you want to understand more why this `__` is used, you can directly read the designed philosophy behind the `stb` libraries https://github.com/nothings/stb/blob/master/docs/stb_howto.txt#L100_L111.
In this case it's a private function used within the scope of the library itself and not exposed through the API.

**Comment by elfring** [comment]
Will corresponding software improvements be continued with [a similar bug report](https://github.com/nothings/stb/issues/277 "Clarification around reserved identifier violations")?

**Comment by karimnaaji** [comment]
Not sure to understand, what do you mean by that?

**Comment by elfring** [comment]
Would you like to update any bundled software?

**Comment by karimnaaji** [comment]
Yes I would do so.

Thanks
