### ISSUE TITLE
Windows?

### ISSUE THREAD

**Issue by pokeahontas** [karimnaaji/vectiler#16]
Hi!
I'd be interested to use you're program to get some 3D Data . 
Can I use it with Windows somehow?

**Comment by karimnaaji** [comment]
Right now you can't but it's possible to port to Windows. 

This exporter is running on a server and I can send you the address if you want to be able to use it on any platform/browser.

**Comment by pokeahontas** [comment]
@karimnaaji that would be great :)

**Comment by karimnaaji** [comment]
@pokeahontas send me an email at karim.naaji@gmail.com and I'll provide you that as a temporary solution.

**Comment by philibert123** [comment]
@karimnaaji Hi good Sir! I would like to use your program as well on windows to get some 3D Data.
Could you provide me as well?

**Comment by karimnaaji** [comment]
Hi, windows support has been added on https://github.com/karimnaaji/vectiler/pull/19. You would need both cmake and Visual studio installed in order to try:
```
git pull
git checkout windows-suppport
mkdir build
cd build
cmake -G "Visual Studio 14 2015 Win64"
```
And open the visual studio solution generated and build the whole solution from there.
