### ISSUE TITLE
Formula pass is old

### ISSUE THREAD

**Issue by tiro105** [karimnaaji/vectiler#17]
`$ cp 3rdparty/aobaker/embree.rb /usr/local/Library/Formula`

Homerew Formula path was changed in 1.0.0.
Now Homebrew Formula path is
`/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/`

**Comment by karimnaaji** [comment]
Hi @tiro105 , I updated the formula in #18 , let me know if that fixes the issue for you and I'll merge this.

**Comment by tiro105** [comment]
thank you!!
