### ISSUE TITLE
Assertion failed error with aobaker 

### ISSUE THREAD

**Issue by robhawkes** [karimnaaji/vectiler#5]
I'm able to get non-AO objs to export but whenever I try and do an AO export I get the following crash:

```bash
$ ./objexport --tilex 19294 --tiley 24642 --tilez 16 --sizehint 512 --nsamples 128 --bakeAO 1
Fetching URL with curl: http://vector.mapzen.com/osm/all/16/19294/24642.json?api_key=vector-tiles-qVaBcRA
Fetched tile: http://vector.mapzen.com/osm/all/16/19294/24642.json?api_key=vector-tiles-qVaBcRA
Save 19294.24642.16.obj
Assertion failed: (in_positions.size() > (unsigned int)(3 * i.v_idx + 2)), function updateVertex, file /Users/Robin/Downloads/vectiler/3rdparty/aobaker/vendor/tinyobj/tiny_obj_loader.h, line 426.
[1]    24818 abort      ./objexport --tilex 19294 --tiley 24642 --tilez 16 --sizehint 512 --nsamples
```

Any idea what's going on? I'd love to get AO baking to work so I can try this out in ViziCities.

**Comment by robhawkes** [comment]
As a follow-up, I noticed in #2 that AO has been crashing for some tiles so I tried one in London instead and it seemed to generate the AO map ok.

**Comment by karimnaaji** [comment]
Thanks for trying this out, this specific issue should be fixed now (https://github.com/karimnaaji/vectiler/commit/5477f68091d64da78bef92ae7f69b8de86e4dabf); but #2  will still be happening for some tiles.

I have some ideas on what could possibly lead to it but didn't try a fix yet; the crash happens while computing a convex hull while generating the uv atlas for the mesh.

This might be related to degenerate geometry (Skinny triangles, edges with no length etc..) which could lead to this crash while computing it, I think that a small _cleanup_ pass while building the geometry should help on that, trying this out as soon as possible.

**Comment by karimnaaji** [comment]
@robhawkes #2 is fixed now. Let me know how that goes.
